<?php
require_once (__DIR__ . "/../vendor/autoload.php");

class InitTest extends \PHPUnit\Framework\TestCase
{
    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        \RW\Email\Client::init(["region" => "us-west-1", "url" => "https://sqs.us-west-1.amazonaws.com/135937294874/email_queue"]);
    }

    public function testInit()
    {
        $this->assertSame(true, true);
    }

    public function testDirectSend()
    {
        $templateId = "59d2be5f18c13";
        $from = ["name" => "Scott", "emailAddress" => "noreply@safecart.com"];
        $to = [["name" => "Scott", "emailAddress" => "swang@revenuewire.com"]];
        $data = ["name" => "Scott", "message" => "可以吧 8"];
        $result = \RW\Email\Client::directSend($templateId, $from, $to, $data);

        $this->assertNotEmpty($result);
    }

    public function testTypeSend()
    {
        $to = [["name" => "Scott", "emailAddress" => "swang@revenuewire.com"]];
        $data = ["name" => "Scott", "message" => "可以吧 8"];
        $result = \RW\Email\Client::typeSend("EMAIL_TYPE_RESET_PASSWORD", null, $to, $data);

        $this->assertNotEmpty($result);
    }
}